/** Standard option lists for the doctor form (mirrored in the backend's apps/doctors/options.py). */

export const SPECIALIZATIONS = [
  "Anesthesiology",
  "Cardiology",
  "Cardiothoracic Surgery",
  "Dentistry",
  "Dermatology",
  "Emergency Medicine",
  "Endocrinology",
  "ENT (Otolaryngology)",
  "Family Medicine",
  "Gastroenterology",
  "General Medicine",
  "General Surgery",
  "Geriatrics",
  "Gynecology & Obstetrics",
  "Hematology",
  "Infectious Diseases",
  "Nephrology",
  "Neurology",
  "Neurosurgery",
  "Oncology",
  "Ophthalmology",
  "Orthopedics",
  "Pathology",
  "Pediatrics",
  "Physiotherapy & Rehabilitation",
  "Plastic Surgery",
  "Psychiatry",
  "Pulmonology",
  "Radiology",
  "Rheumatology",
  "Urology",
  "Vascular Surgery",
] as const;

export const DEPARTMENTS = [
  "Anesthesiology",
  "Cardiology",
  "Critical Care (ICU)",
  "Dental",
  "Dermatology",
  "Emergency",
  "ENT",
  "Gastroenterology",
  "General Medicine",
  "General Surgery",
  "Gynecology & Obstetrics",
  "Laboratory & Pathology",
  "Nephrology",
  "Neurology",
  "Oncology",
  "Ophthalmology",
  "Orthopedics",
  "Pediatrics",
  "Physiotherapy",
  "Psychiatry",
  "Pulmonology",
  "Radiology",
  "Urology",
] as const;

export const DESIGNATIONS = [
  "Intern",
  "Resident",
  "Senior Resident",
  "Junior Consultant",
  "Consultant",
  "Senior Consultant",
  "Specialist",
  "Associate Professor",
  "Professor",
  "Head of Department",
  "Medical Superintendent",
  "Chief Medical Officer",
  "Visiting Consultant",
] as const;
